# Data Cleaning & Pandas Joins

## Step 1: Upload CSV Dataset

In [1]:
from google.colab import files
uploaded = files.upload()

Saving assesment_dataset.csv to assesment_dataset.csv

## Step 2: Import required libraries and load dataset

In [2]:
import pandas as pd

df = pd.read_csv("assesment_dataset.csv")

In [3]:
# Preview the first few rows
df.head()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2023,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,930995,ANZSIC06 divisions A-S (excluding classes K633...
1,2023,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,821630,ANZSIC06 divisions A-S (excluding classes K633...
2,2023,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,84354,ANZSIC06 divisions A-S (excluding classes K633...
3,2023,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25010,ANZSIC06 divisions A-S (excluding classes K633...
4,2023,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,832964,ANZSIC06 divisions A-S (excluding classes K633...

## Step 3: Data Cleaning

### 1. Basic Info and Null Value Check

In [4]:
# Get structure of the dataset
df.info()

# Check for missing/null values
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50985 entries, 0 to 50984
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         50985 non-null  int64
 1   Industry_aggregation_NZSIOC  50985 non-null  object
 2   Industry_code_NZSIOC         50985 non-null  object
 3   Industry_name_NZSIOC         50985 non-null  object
 4   Units                        50985 non-null  object
 5   Variable_code                50985 non-null  object
 6   Variable_name                50985 non-null  object
 7   Variable_category            50985 non-null  object
 8   Value                        50985 non-null  object
 9   Industry_code_ANZSIC06       50985 non-null  object
dtypes: int64(1), object(9)
memory usage: 3.9+ MB

Year                           0
Industry_aggregation_NZSIOC    0
Industry_code_NZSIOC           0
Industry_name_NZSIOC           0
Units                          0
Variable_code                  0
Variable_name                  0
Variable_category              0
Value                          0
Industry_code_ANZSIC06         0
dtype: int64

### 2. Descriptive Statistics

In [5]:
# Show descriptive statistics for numeric columns
df.describe()

               Year
count  50985.000000
mean    2018.000000
std        3.162309
min     2013.000000
25%     2015.000000
50%     2018.000000
75%     2021.000000
max     2023.000000

### 3. Drop Duplicate Rows (if any)

In [6]:
# Check and drop duplicate rows
print("Duplicates before:", df.duplicated().sum())
df = df.drop_duplicates()
print("Duplicates after:", df.duplicated().sum())

Duplicates before: 0
Duplicates after: 0

## Step 4:Spliting Dataset

In [20]:
# DataFrame 1: Basic industry information (unique values)
df1 = df[['Industry_code_NZSIOC', 'Industry_name_NZSIOC', 'Units']].drop_duplicates()

# DataFrame 2: Financial variables (many-to-one relationship with industry)
df2 = df[['Industry_code_NZSIOC', 'Variable_name', 'Value', 'Year']]

##  Step 5: Perform Joins Between df1 and df2

In [21]:
df1['Industry_code_NZSIOC'] = df1['Industry_code_NZSIOC'].astype(str)
df2['Industry_code_NZSIOC'] = df2['Industry_code_NZSIOC'].astype(str)

/tmp/ipython-input-21-3284072568.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Industry_code_NZSIOC'] = df2['Industry_code_NZSIOC'].astype(str)

### 5.1 Inner Join (only matching records)

In [28]:
inner_join = pd.merge(df2, df1, on='Industry_code_NZSIOC', how='inner')
print("Inner Join Result:")
inner_join.head(25)

Inner Join Result:

,Industry_code_NZSIOC,Variable_name,Value,Year,Industry_name_NZSIOC,Units
0,99999,Total income,930995,2023,All industries,Dollars (millions)
1,99999,Total income,930995,2023,All industries,Dollars
2,99999,Total income,930995,2023,All industries,Percentage
3,99999,"Sales, government funding, grants and subsidies",821630,2023,All industries,Dollars (millions)
4,99999,"Sales, government funding, grants and subsidies",821630,2023,All industries,Dollars
5,99999,"Sales, government funding, grants and subsidies",821630,2023,All industries,Percentage
6,99999,"Interest, dividends and donations",84354,2023,All industries,Dollars (millions)
7,99999,"Interest, dividends and donations",84354,2023,All industries,Dollars
8,99999,"Interest, dividends and donations",84354,2023,All industries,Percentage
9,99999,Non-operating income,25010,2023,All industries,Dollars (millions)
10,99999,Non-operating income,25010,2023,All industries,Dollars
11,99999,Non-operating income,25010,2023,All industries,Percentage
12,99999,Total expenditure,832964,2023,All industries,Dollars (millions)
13,99999,Total expenditure,832964,2023,All industries,Dollars
14,99999,Total expenditure,832964,2023,All industries,Percentage
15,99999,Interest and donations,55267,2023,All industries,Dollars (millions)
16,99999,Interest and donations,55267,2023,All industries,Dollars
17,99999,Interest and donations,55267,2023,All industries,Percentage
18,99999,Indirect taxes,7426,2023,All industries,Dollars (millions)
19,99999,Indirect taxes,7426,2023,All industries,Dollars
20,99999,Indirect taxes,7426,2023,All industries,Percentage
21,99999,Depreciation,30814,2023,All industries,Dollars (millions)
22,99999,Depreciation,30814,2023,All industries,Dollars
23,99999,Depreciation,30814,2023,All industries,Percentage
24,99999,Salaries and wages paid,147663,2023,All industries,Dollars (millions)

### 5.2 Left Join (all from df2 + matched from df1)

In [29]:
left_join = pd.merge(df2, df1, on='Industry_code_NZSIOC', how='left')
print("Left Join Result:")
left_join.head(30)

Left Join Result:

,Industry_code_NZSIOC,Variable_name,Value,Year,Industry_name_NZSIOC,Units
0,99999,Total income,930995,2023,All industries,Dollars (millions)
1,99999,Total income,930995,2023,All industries,Dollars
2,99999,Total income,930995,2023,All industries,Percentage
3,99999,"Sales, government funding, grants and subsidies",821630,2023,All industries,Dollars (millions)
4,99999,"Sales, government funding, grants and subsidies",821630,2023,All industries,Dollars
5,99999,"Sales, government funding, grants and subsidies",821630,2023,All industries,Percentage
6,99999,"Interest, dividends and donations",84354,2023,All industries,Dollars (millions)
7,99999,"Interest, dividends and donations",84354,2023,All industries,Dollars
8,99999,"Interest, dividends and donations",84354,2023,All industries,Percentage
9,99999,Non-operating income,25010,2023,All industries,Dollars (millions)
10,99999,Non-operating income,25010,2023,All industries,Dollars
11,99999,Non-operating income,25010,2023,All industries,Percentage
12,99999,Total expenditure,832964,2023,All industries,Dollars (millions)
13,99999,Total expenditure,832964,2023,All industries,Dollars
14,99999,Total expenditure,832964,2023,All industries,Percentage
15,99999,Interest and donations,55267,2023,All industries,Dollars (millions)
16,99999,Interest and donations,55267,2023,All industries,Dollars
17,99999,Interest and donations,55267,2023,All industries,Percentage
18,99999,Indirect taxes,7426,2023,All industries,Dollars (millions)
19,99999,Indirect taxes,7426,2023,All industries,Dollars
20,99999,Indirect taxes,7426,2023,All industries,Percentage
21,99999,Depreciation,30814,2023,All industries,Dollars (millions)
22,99999,Depreciation,30814,2023,All industries,Dollars
23,99999,Depreciation,30814,2023,All industries,Percentage
24,99999,Salaries and wages paid,147663,2023,All industries,Dollars (millions)
25,99999,Salaries and wages paid,147663,2023,All industries,Dollars
26,99999,Salaries and wages paid,147663,2023,All industries,Percentage
27,99999,Redundancy and severance,269,2023,All industries,Dollars (millions)
28,99999,Redundancy and severance,269,2023,All industries,Dollars
29,99999,Redundancy and severance,269,2023,All industries,Percentage

### 5.3 Right Join (all from df1 + matched from df2)

In [30]:
right_join = pd.merge(df2, df1, on='Industry_code_NZSIOC', how='right')
print("Right Join Result:")
right_join.head(30)

Right Join Result:

,Industry_code_NZSIOC,Variable_name,Value,Year,Industry_name_NZSIOC,Units
0,99999,Total income,930995,2023,All industries,Dollars (millions)
1,99999,"Sales, government funding, grants and subsidies",821630,2023,All industries,Dollars (millions)
2,99999,"Interest, dividends and donations",84354,2023,All industries,Dollars (millions)
3,99999,Non-operating income,25010,2023,All industries,Dollars (millions)
4,99999,Total expenditure,832964,2023,All industries,Dollars (millions)
5,99999,Interest and donations,55267,2023,All industries,Dollars (millions)
6,99999,Indirect taxes,7426,2023,All industries,Dollars (millions)
7,99999,Depreciation,30814,2023,All industries,Dollars (millions)
8,99999,Salaries and wages paid,147663,2023,All industries,Dollars (millions)
9,99999,Redundancy and severance,269,2023,All industries,Dollars (millions)
10,99999,Salaries and wages to self employed commission...,1639,2023,All industries,Dollars (millions)
11,99999,Purchases and other operating expenses,566979,2023,All industries,Dollars (millions)
12,99999,Non-operating expenses,23176,2023,All industries,Dollars (millions)
13,99999,Opening stocks,80778,2023,All industries,Dollars (millions)
14,99999,Closing stocks,88197,2023,All industries,Dollars (millions)
15,99999,Surplus before income tax,105450,2023,All industries,Dollars (millions)
16,99999,Total assets,2831894,2023,All industries,Dollars (millions)
17,99999,Current assets,861255,2023,All industries,Dollars (millions)
18,99999,Fixed tangible assets,681890,2023,All industries,Dollars (millions)
19,99999,Other assets,1288749,2023,All industries,Dollars (millions)
20,99999,Total equity and liabilities,2831893,2023,All industries,Dollars (millions)
21,99999,Shareholders funds or owners equity,957410,2023,All industries,Dollars (millions)
22,99999,Current liabilities,1074693,2023,All industries,Dollars (millions)
23,99999,Other liabilities,799791,2023,All industries,Dollars (millions)
24,99999,Total income per employee count,464600,2023,All industries,Dollars (millions)
25,99999,Surplus per employee count,52600,2023,All industries,Dollars (millions)
26,99999,Current ratio,80,2023,All industries,Dollars (millions)
27,99999,Quick ratio,72,2023,All industries,Dollars (millions)
28,99999,Return on equity,11,2023,All industries,Dollars (millions)
29,99999,Return on total assets,4,2023,All industries,Dollars (millions)

### 5.4 Outer Join (all records from both)

In [31]:
outer_join = pd.merge(df2, df1, on='Industry_code_NZSIOC', how='outer')
print("Outer Join Result:")
outer_join.head(30)

Outer Join Result:

,Industry_code_NZSIOC,Variable_name,Value,Year,Industry_name_NZSIOC,Units
0,99999,Total income,930995,2023,All industries,Dollars (millions)
1,99999,Total income,930995,2023,All industries,Dollars
2,99999,Total income,930995,2023,All industries,Percentage
3,99999,"Sales, government funding, grants and subsidies",821630,2023,All industries,Dollars (millions)
4,99999,"Sales, government funding, grants and subsidies",821630,2023,All industries,Dollars
5,99999,"Sales, government funding, grants and subsidies",821630,2023,All industries,Percentage
6,99999,"Interest, dividends and donations",84354,2023,All industries,Dollars (millions)
7,99999,"Interest, dividends and donations",84354,2023,All industries,Dollars
8,99999,"Interest, dividends and donations",84354,2023,All industries,Percentage
9,99999,Non-operating income,25010,2023,All industries,Dollars (millions)
10,99999,Non-operating income,25010,2023,All industries,Dollars
11,99999,Non-operating income,25010,2023,All industries,Percentage
12,99999,Total expenditure,832964,2023,All industries,Dollars (millions)
13,99999,Total expenditure,832964,2023,All industries,Dollars
14,99999,Total expenditure,832964,2023,All industries,Percentage
15,99999,Interest and donations,55267,2023,All industries,Dollars (millions)
16,99999,Interest and donations,55267,2023,All industries,Dollars
17,99999,Interest and donations,55267,2023,All industries,Percentage
18,99999,Indirect taxes,7426,2023,All industries,Dollars (millions)
19,99999,Indirect taxes,7426,2023,All industries,Dollars
20,99999,Indirect taxes,7426,2023,All industries,Percentage
21,99999,Depreciation,30814,2023,All industries,Dollars (millions)
22,99999,Depreciation,30814,2023,All industries,Dollars
23,99999,Depreciation,30814,2023,All industries,Percentage
24,99999,Salaries and wages paid,147663,2023,All industries,Dollars (millions)
25,99999,Salaries and wages paid,147663,2023,All industries,Dollars
26,99999,Salaries and wages paid,147663,2023,All industries,Percentage
27,99999,Redundancy and severance,269,2023,All industries,Dollars (millions)
28,99999,Redundancy and severance,269,2023,All industries,Dollars
29,99999,Redundancy and severance,269,2023,All industries,Percentage

## Save & Export Merged Data

In [32]:
inner_join.to_csv("merged_data.csv", index=False)
from google.colab import files
files.download("merged_data.csv")